config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "ideas#index"
  resources :ideas
  get 'about' => 'static_pages#about'
  get 'random' => 'static_pages#random'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/idea.rb
class Idea < ApplicationRecord
    validates :description, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  def create
    @idea = Idea.create(description: params[:idea][:description], author: params[:idea][:author])
    if @idea.valid?
      flash[:success] = "Your idea has been posted!"
    else
      flash[:alert] = "Woops! Looks like there has been an error!"
    end
    redirect_to root_path
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update(idea_params)
      flash[:success] = "The idea has been updated!"
      redirect_to root_path
    else
      flash[:alert] = "Woops! Looks like there has been an error!"
      redirect_to edit_idea_path(params[:id])
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    flash[:success] = "The idea was susccessfully deleted!"
    redirect_to root_path
  end

  private

  def idea_params
    params.require(:idea).permit(:description, :author)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def about

    end

    def random
        @idea = Idea.order("RAND()").first
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ideas/edit.html.erb
<h1> Revise Idea </h1>

<%= simple_form_for @idea, method: :patch do |f| %>
<%= f.input :description %>
  <%= f.input :author %>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/ideas/index.html.erb
 <h2> Ideas with Author </h2>
 
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Add Idea
</button>
<br> <br>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Idea</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for Idea.new do |f| %>
      <div class="modal-body">
          <%= f.input :description %>
          <%= f.input :author %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
       <% end %> <br>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h4>Interesting Ideas.</h4>
  </div>
</div>

<% @ideas.each do |idea| %>
<div class="card">
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= idea.description %></p>
      <footer class="blockquote-footer">by <%= idea.author %></footer>
    </blockquote>
    <br>
    <%= link_to 'Delete', idea_path(idea), class: 'btn btn-sm btn-danger', data: {"turbo-confirm": "Are you sure?", "turbo-method": :delete} %>
    <%= link_to 'Revise', edit_idea_path(idea), class: 'btn btn-sm btn-success' %>
  </div>
</div>
<% end %>

<div class="d-flex justify-content-center will_pagination">
  <%= will_paginate @ideas %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideatorss</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://fonts.googleapis.com/css2?family=Dosis&family=Open+Sans&family=Pacifico&display=swap" rel="stylesheet">  </head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <body>
    <div id = "wrap">
      <%= render 'shared/nav' %>

      <div class = "container">
      <div class = "row">
      <div class = "col-xs-12 col-md-6 col-md-offset-3">
        <%= render 'shared/flash_messages' %>
        <%= yield %>
      </div>
    </div>
  </div>
  
    </div>
    <%= render 'shared/footer' %>
  
  </body>
  </html>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <% if message_type == "notice" %>
      <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
    <% elsif message_type == "alert" %>
      <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
    <% else %>
      <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
    <% end %>
  <% end %>

app/views/shared/_footer.html.erb
<div class="footer text-center">
      <p>&copy; TECHBRAIN (<%= Date.today.year%>/<%= Date.today.month%>/<%= Date.today.day%>) All Rights Reserved</p>
    </div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Ideatorss</a>
          <div class= "d-inline-flex justify-content-end">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="/">All Ideas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/about">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="random">Random</a>
              </li>
            </ul>
          </div>
        </div>
        </div>
      </nav>

app/views/static_pages/about.html.erb
<h1> About page </h1>
<p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore eum natus saepe assumenda velit dolorem eligendi hic vitae possimus quis quod, voluptates cumque rem ut.<p>

<p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates, sunt mollitia quod aperiam inventore quidem magnam, deleniti consequatur recusandae cumque similique aspernatur nisi obcaecati dicta, exercitationem nulla officiis doloremque dolor expedita sint alias maxime saepe! Laboriosam et iste a quasi vel veritatis architecto neque sit nobis. Cumque minima sed quia!</p>

app/views/static_pages/random.html.erb
<% if @idea.present? %>

    <%= link_to 'Inspire Me', random_path, class: 'btn btn-primary btn-block' %>

    <div class="card">
    <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @idea.description %></p>
      <footer class="blockquote-footer">by <%= @idea.author %></footer>
    </blockquote>
    <br>
    <%= link_to 'Delete', idea_path(@idea), class: 'btn btn-sm btn-danger', data: {"turbo-confirm": "Are you sure?", "turbo-method": :delete} %>
    <%= link_to 'Revise', edit_idea_path(@idea), class: 'btn btn-sm btn-success' %>
    </div>
    </div>
<% end %>